package es.tfm.records.application.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.UUID;

/**
 * Attachment within a case detail.
 */
@Schema(description = "Case attachment reference")
public record CaseAttachmentDto(
        @Schema(description = "Attachment unique identifier")
        UUID id,
        @Schema(description = "Attachment file name", example = "supporting-doc.pdf")
        String name,
        @Schema(description = "Attachment type", example = "SUPPORTING_DOCUMENT")
        String type,
        @Schema(description = "File size in bytes", example = "2048576")
        long size,
        @Schema(description = "Who uploaded this attachment", example = "Citizen")
        String uploadedBy,
        @Schema(description = "Upload timestamp")
        Instant uploadedAt,
        @Schema(description = "Whether this document has been electronically signed", example = "true")
        boolean signed,
        @Schema(description = "Whether original upload artifact is available", example = "true")
        boolean hasOriginal,
        @Schema(description = "Whether signed artifact is available", example = "true")
        boolean hasSigned,
        @Schema(description = "CSV verification code for signed documents", example = "AB12CD34EF56")
        String csvCode,
        @Schema(description = "Exit registry number (NRS)", example = "RS/URB/2026/000001")
        String exitNumber,
        @Schema(description = "Entry registry number (NRE)", example = "RE/URB/2026/000001")
        String entryNumber,
        @Schema(description = "Whether this document was auto-generated by the system", example = "false")
        boolean generated
) {}
