spring:
  datasource:
    url: jdbc:h2:mem:records_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

signing:
  keystore:
    password: ${SIGNING_KEYSTORE_PASSWORD:changeit}

jwt:
  secret: ${JWT_SECRET:ZGV2LXNlY3JldC1rZXktZm9yLXRlc3RpbmctcHVycG9zZXMtb25seS1kb25vdC11c2UtaW4tcHJvZHVjdGlvbg==}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

mailing:
  enabled: true
  queue:
    enabled: false
  verification-base-url: http://localhost:4200/sede/verificar-email
  password-reset-base-url: http://localhost:4200/sede/restablecer-contrasena
  from:
    email: no-reply@records.local
    name: Records

logging:
  level:
    es.tfm.records: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
